#+TITLE: Intro to Coffee Roasting & Tasting

Description of class:

Darkly colored, bitter, and slightly acidic, coffee is the most
popular drink in the world. The earliest credible evidence of coffee
drinking in the form of the modern beverage appears in modern-day
Yemen from the mid-15th century in Sufi shrines, where coffee seeds
were first roasted and brewed in a manner similar to current methods.

In this 3-hr class you will learn how to roast your own coffee beans
on our Behmor Coffee Roaster as well as normal machine cleaning and
maintenance. Try 5 different types of freshly roasted coffee and take
home 1/2 pound of ready-to-grind beans.  No experience necessary. For
members who have completed the online portion of the coffee roasting
badge, this class will include facilitator check-out.

Join us for an afternoon of coffee roasting & tasting!

* Coffees

| Label | Name                      | Origin                          | Bean type          | Height (masl) | Processing | Profile | Time to first crack  | Left after | roast/green |
|-------+---------------------------+---------------------------------+--------------------+---------------+------------+---------+----------------------+------------+-------------|
| A     | El Conquistador           | Costa Rica, Tarrazú             | Caturra/Catuai     |     1200-1900 | Washed     | P4      | 14'24"               | 40"        |        0.88 |
| B     | Kona Extra Fancy          | Hawaii, Mauka Honaunau District | Kona               |           600 | Washed     | P4      | 11'33"               | 40"        |        0.88 |
| C     | Jason Farms Geisha Washed | Panama, Volcan High Lands       | Geisha             |     1350-1700 | Washed     | P4      | 11'26"               | 40"        |        0.88 |
| D     | Kintanamani               | Bali, Kintamani Highlands       | Bourbon            |     1200-1600 | Natural    | P4      | 12'50                | 40"        |        0.86 |
| E     | Konga G1                  | Ethiopia, Yirgacheffe           | Ethiopian Heirloom |     1850-2100 | Washed     | P4      | 12'32" (very slight) | 40"        |        0.89 |

** Introduction

** Preparing

*** Importance of weighing

Compare one table spoon of two types of beans

** Tasting

Try to look for

- Bitterness
- Brightness/acidity
- Sweetness (between sweet and tart)


- Panama: Janson Farms Geisha, Volcan High Lands

Balanced, juicy, crisp, mild, and smooth with flavor notes of milk
chocolate, caramel, orange blossom, lemon, black cherry, and
blueberry!

- Bali: Organic Kintamani, Kintamani Highlands

Lots of Body with very high acidity with notes of Strawberry,
Watermelon, Papaya and Cane Sugar giving it a very sweet taste.

- Costa Rica: El Conquistador, Tarrazu

This Costa Rican coffee bean has the fruity, nutty characteristics
that make this region’s coffees famous. Try before you stock up with a
1/2 pound sample!

- Ethiopia: Organic Konga G1, Yirgacheffe

The Ethiopian Yirgacheffe has floral and fruit notes like pear and
citrus and sweet honey.

- Hawaii: Kona Extra Fancy, Mauku Honaunau District

This is the highest grade of Kona Coffee available and produces a
smooth, bold, rich flavor and an aroma that is truly and utterly
unforgettable.

** Where to buy green beans

https://www.coffeebeancorral.com (20% tomorrow for Cyber Monday)
https://www.sweetmarias.com/

** Scale recommended

SC Series Precision Digital Kitchen Weight Scale, Food Measuring
Scale, 2kg x 0.1g (Silver), AMW-SC-2KG ($34)

https://smile.amazon.com/gp/product/B001RF3XJ2

** French presses

One cup: MIRA 12 oz French Press ($23)
https://www.mirabrands.com/products/12-oz-french-press

They also have 20 oz and 34 oz

Huge: SterlingPro French Press (1.75L/60 oz)
https://smile.amazon.com/gp/product/B014U0ZNG6

All stainless steel are pretty much the same.
