#+TITLE: Intro to Coffee Roasting & Tasting

This material is part of a [[makehaven.org][MakeHaven]] event on <2022-11-27 Sun 14:00>.

In the event we will learn how to roast your own coffee beans on our
[[https://www.makehaven.org/i/7944][Behmor Coffee Roaster]] as well as normal machine cleaning and
maintenance.

We will also try 5 different types of coffee and take home samples of
freshly roasted coffee. No experience necessary. For members who have
completed the [[https://www.makehaven.org/i/7944][online portion]] of the coffee roasting badge, this event
will serve as the facilitator check-out, so you will get the badge for
the Behmor at the end.

* Roasting

Try to keep it simple. Vary only one variable at a time. For our
tasting I kept all variables in the roasting the same, and just
changed the type of bean. The time to first crack varies substantially
per coffee type:

| Label | Weight setting | Preheat | Profile used | Time to first crack  | Left after first crack | roast/green |
|-------+----------------+---------+--------------+----------------------+------------------------+-------------|
| A     | 1/4 lb         | 1'      | P4           | 14'24"               | 40"                    |        0.88 |
| B     | 1/4 lb         | 1'      | P4           | 11'33"               | 40"                    |        0.88 |
| C     | 1/4 lb         | 1'      | P4           | 11'26"               | 40"                    |        0.88 |
| D     | 1/4 lb         | 1'      | P4           | 12'50                | 40"                    |        0.86 |
| E     | 1/4 lb         | 1'      | P4           | 12'32" (very slight) | 40"                    |        0.89 |

Pressing "C" after first roast gives an estimate of the time to second
crack. The closer to second crack the darker the roast.

For in more information consult the [[file:Behmor 2000AB 120v Operation Manual V25.2 7.12.2021 BW Inspired.pdf][manual of the roaster]].

The coffee loses weight after roasting, the ratio of the weight of
roasted coffee to green coffee varies per coffee type:

| Label | Initial weight | weight roasted / weight green | Roasted weight |
|-------+----------------+-------------------------------+----------------|
| A     | 120 grams      |                          0.88 | 105.6 grams    |
| B     | 120 grams      |                          0.88 | 105.6 grams    |
| C     | 120 grams      |                          0.88 | 105.6 grams    |
| D     | 120 grams      |                          0.86 | 103.2 grams    |
| E     | 120 grams      |                          0.89 | 106.8 grams    |

This important if you will try to plan ahead for much you will
consume. The 120 grams will make about 6.5 cups of coffee.

Coffee needs to "degas" to get a great flavor. A light roast flavor
peaks at around 10 days after roasting. Darker roasts need to degas
for less time. Leave the coffee not covered for at least a day after
roasting.

** Where to buy green beans

https://www.coffeebeancorral.com (20% tomorrow for Cyber Monday)
https://www.sweetmarias.com/

* Preparing

We will keep it simple here too. We focus on only one easy but great
method (french press).

Pick a ratio of coffee to water (measured by weight). I use 1:16 (it
is on the strong side, but that's better IMO and it is easy to
multiply 2).

Be patient: let the coffee brew for about 8 minutes before trying it.

Water temperature does not matter (as long as it is hot), you cannot
really burn the coffee. But you can burn your tongue, so better to
start at around 200° Fahrenheit so that it is "cold" enough to try
after 10 minutes brewing.

** Equipment

*** Scale recommended

SC Series Precision Digital Kitchen Weight Scale, Food Measuring
Scale, 2kg x 0.1g (Silver), AMW-SC-2KG ($34)

https://smile.amazon.com/gp/product/B001RF3XJ2

*** French presses

One cup: MIRA 12 oz French Press ($23)
https://www.mirabrands.com/products/12-oz-french-press

They also have 20 oz and 34 oz

Huge: SterlingPro French Press (1.75L/60 oz)
https://smile.amazon.com/gp/product/B014U0ZNG6

All stainless steel presses that I have seen are pretty much the same.

*** Grinders

Large, fast and fits mason jars: Hario Ceramic Coffee Mill - 'Skerton
Plus' https://smile.amazon.com/gp/product/B01LXZACFB/

* Tasting

Try to look for

- Bitterness: any "regular" coffee vs any coffee tried here
- Brightness (acidity): E vs F
- Sweetness (between tart and sweet) A vs C
- Aroma: B vs D
- Body: A vs B
- Complexity/Balance
- Flavors:
  + Chocolaty
  + Nutty
  + Buttery
  + Flowery
  + Wine
  + Earthy
  + Fruitty (all)
  + Spicy (none?)
