#+TITLE: Intro to Coffee Roasting & Tasting

This material is part of a [[makehaven.org][MakeHaven]] event on <2023-10-07 Sat>.

In this event we will learn how to roast your own coffee beans on our
[[https://www.makehaven.org/i/7944][Behmor Coffee Roaster]] as well as normal machine cleaning and
maintenance.

We will also taste and compare 5 different types of coffee, blinding
them and just referring to them by labels (A, B, C, D, E) until the
end of the event.

At the end of the event we will take home samples of freshly roasted
coffee.

For MakeHaven members who have completed the [[https://www.makehaven.org/i/7944][online portion]] of the
coffee roasting badge, this event will serve as the facilitator
check-out, so you will get the badge for the Behmor at the end.

* Roasting

Try to keep it simple. Vary only one variable at a time. For our
tasting I kept all variables in the roasting the same, and just
changed the type of bean. The time to first crack varies substantially
per coffee type.

For all types of coffee the time to first crack was more than the
default time for the profile so I had to add more time (with the +
button) while roasting.

Pressing "C" after the first crack gives an estimate of the time to
second crack. *This is the most important part of the roasting*. The
closer to second crack the darker the roast. I obtained a relatively
light roast for all beans by activating the cooling at about *50
seconds* after the first crack. But this time can vary per bean type.

If you reduce the heat right after the first crack (pressing P3 or P4
to set the power to 50% or 75%), you can extend the time to second
crack (might even need to press "+" or "C" again). If you extend the
time by reducing the heat after first crack, your coffee would gain in
"sweetness" but lose in "brightness".

If you are roasting a type of coffee for the first time, be at the
machine from the time that it starts beeping for the first time. Every
coffee type is quite different and you might burn your beans if you
are not paying attention.

For more information on settings consult the [[file:behmor_manual.pdf][manual of the roaster]].

The coffee loses weight after roasting, the ratio of the weight of
roasted coffee to green coffee varies per coffee type, but is around
0.85-0.9.

This is important if you will try to plan ahead for much you will
consume. A quarter pound roasted ends up making about 6-7 cups of
coffee (depending on how strong the coffee is).

Coffee needs to "degas" after roasting. The flavor of a light roast
coffee flavor peaks at around 10 days after roasting. Darker roasts
need to degas for less time. Leave the coffee not covered for at least
a day after roasting to help with the degassing process.

** Where to buy green beans

- https://www.coffeebeancorral.com
- https://www.sweetmarias.com/

* Preparing

We will keep it simple here too. We focus on only one easy but great
method (french press).

Pick a ratio of coffee to water (measured by weight). I use *1:16* (it
is on the strong side, but that's better IMO and it is easy to
multiply by 2, 4 times).

Grind your coffee just before preparing it. I do a medium grind,
sometimes people recommended coarse grinds for french press but they
tend extract less coffee.

Do not grind a bunch for a couple of days, the coffee will be exposed
to a lot of air and lose most of its flavor.

Water temperature does not matter (as long as it is hot), you cannot
really burn the coffee. But you can burn your tongue, so better to
start at around 200° Fahrenheit so that it is "cold" enough to try
after 10 minutes of brewing.

After adding the water, be patient: let the coffee brew for about 8
minutes before trying it. In between, around 4 minutes, I like to
"break" the coffee to expose the coffee at the top to more water and
so that the big grounds floating on top go to the bottom. You can then
choose to remove the big grounds (more expensive grinders would have
more consistency, so less of those) that are still floating on top
with a spoon. Then wait another 4-5 minutes without touching the
coffee, so that it settles.

When you push the filter do it slowly and do not press it all the way,
so that you do not mix the grounds that are on the bottom. That way
there are less likely to end up in the cup. For the same reason, pour
the coffee slowly.

** Equipment

*** Scale recommended

- SC Series Precision Digital Kitchen Weight Scale
  https://smile.amazon.com/gp/product/B001RF3XJ2

*** French presses

- One cup: MIRA 12 oz French Press ($23)
  https://www.mirabrands.com/products/12-oz-french-press

  MIRA also has 20 oz and 34 oz. We used a couple of MIRA presses for
  the event.

- Largest press that I have found: SterlingPro French Press (1.75L/60
  oz) https://smile.amazon.com/gp/product/B014U0ZNG6

  All stainless steel presses that I have tried are very similar. I
  like stainless steel because they last a lifetime and because they
  keep the heat very well.

*** Grinders

Good video: https://www.youtube.com/watch?v=bgjvLQu5NlE

**** Hand grinders

- Small (for one person), very good for traveling: Porlex Mini
  Stainless Steel Coffee Grinder
  https://www.porlexgrinders.com/products/porlex-mini-grinder-ii

- Small, better (but more expensive) than previous one:
  Knock Aergrind https://madebyknock.com/products/aergrind

- Large, OK (but not great) for french press, fast and bottom
  container fits mason jar: Hario Ceramic Coffee Mill - 'Skerton Plus'
  https://www.hario-usa.com/products/ceramic-coffee-mill-skerton-plus

- Premium, can do even espresso: Kinu M47 Classic
  https://kinugrinders.com/product/m47-classic/

Premium grinders have stainless steel burrs (instead of ceramic), so
they will last longer.

**** Electric grinders

- Do not buy any with blades instead of burr, the grind would be very
  inconsistent. Better a cheap hand grinder than electric grinders
  with blades.
- Entry level, same as the one that we have at MakeHaven (OK for
  french press, not good for espresso): Baratza Encore Coffee Mill
  https://www.willoughbyscoffee.com/MPS.html

*** Water kettle

- Willow & Everett Gooseneck Electric Kettle with Temperature Control
  & Presets - 1L, Stainless Steel
  https://smile.amazon.com/gp/product/B06XPLM49J

I like the temperature presets (also helpful for making different
types of tea at the right temperature) and always set it to 200°
Fahrenheit for coffee. I also like the gooseneck to pour the water
slowly and more precisely, exposing more of the coffee to the
water. But this is really the least important part of the
equipment. Pretty much any kettle works well, you just might have to
wait longer so that your coffee cools down enough to drink it.

* Tasting

Try to look for

- Bitterness:
- Brightness (acidity): A vs C
- Sweetness (between tart and sweet) C vs D
- Aroma: A vs B
- Body: A vs D
- Complexity/Balance
- Flavors:
  + Chocolaty
  + Nutty
  + Buttery
  + Flowery
  + Wine
  + Earthy
  + Fruity (all)
  + Spicy (none?)


** Coffee scores (according to Coffee Bean Corral)

|   | Coffee                      | Brightness | Sweetness | Aroma | Body | Complexity | Balance | Spicy | Chocolaty | Nutty | Buttery | Fruity | Flowery | Wine | Earthy |
|---+-----------------------------+------------+-----------+-------+------+------------+---------+-------+-----------+-------+---------+--------+---------+------+--------|
| A | DR of Congo Organic Mapendo |        *7* |         5 |   *4* |  *3* |          6 |       5 |     ? |         ? |     ? |       ? |      ? |       ? |    ? |      ? |
| B | Papua New Guinea Arokara AA |          5 |         3 |   *7* |    5 |        *7* |       7 |     1 |         4 |     1 |       1 |      4 |       3 |    3 |      4 |
| C | Sumatra Mutu Batak          |        *3* |       *2* |     5 |  *6* |          6 |     *4* |     3 |         1 |     1 |       4 |      1 |       1 |    1 |      4 |
| D | Panama Janson Farms Geisha  |          6 |       *7* |     5 |    5 |          6 |       5 |     1 |         3 |     1 |       2 |      4 |       4 |    1 |      1 |
| E | La Gladiola Tarrazu         |          4 |         4 |     5 |    6 |        *4* |     *6* |     1 |         3 |     1 |       2 |      4 |       1 |    1 |      1 |

The scale for Brightness, Sweetness, Aroma, Body, Complexity, and
Balance is 1-7 (in bold, comparison during testing). For flavors the
scale is 1-4.

* Un-blinding the coffees

|   | Coffee                      | Origin                              | Bean type                | Process    | Price     | Where to buy                                                                              |
|---+-----------------------------+-------------------------------------+--------------------------+------------+-----------+-------------------------------------------------------------------------------------------|
| A | DR of Congo Organic Mapendo | Mapendo, DR of Congo                |                          |            | ?         | No longer available                                                                       |
| B | Arokara AA                  | Eastern Highlands, Papua New Guinea | Typica, Bourbon, Arusha  | Washed     | $7.70/lb  | https://www.coffeebeancorral.com/product/Papua-New-Guinea-AA-Arokara__PNGAROKA.aspx       |
| C | Sumatra Mutu Batak          | Lintong, Indonesia                  | Ateng, Jember, Garundang | Wet Hulled | $8.25/lb  | https://www.coffeebeancorral.com/product/Sumatra-Mutu-Batak-Lintong__SUMMUTUBATAK.aspx    |
| D | Janson Farms Geisha         | Volcan High Lands, Panamá           | Geisha                   | Washed     | $34.45/lb | https://www.coffeebeancorral.com/product/Panama-Janson-Farm-Geisha-531__PANGEISHA.aspx    |
| E | La Gladiola Tarrazu         | Tarrazú, Costa Rica                 | Caturra/Catuai           | Washed     | $7.40/lb  | https://www.coffeebeancorral.com/product/Colombia-Geisha-Rebel-Washed__COLWASHGEISHA.aspx |

- Papua New Guinea Arokara AA

Papua New Guinea coffees are known for their complex acidity and
bountiful variety due to cultural and topographical diversity––few
plantations are large, and most happen to be small plots. Processing
methods are constantly being updated to ensure the best coffee year
after year.

This specific Arakara AA hails from the Arokara Cooperative, a partner
of plantations in the Eastern Highlands of Papua, New
Guinea. Recently, the plantations have been transferred to the
original owners who believe in a chemical-free production process. The
coffee’s cherry is hand-picked by the clan, immediately pulped, and
fermented in cement vats for three days. Then, the coffee is washed
with the Aru River’s water and sun-dried for seven to twelve days. The
plantations hire up to 60 assistants to the clan cherry
pickers––nearly 12,000 people depend on this process for income to
support their families.

Cupping notes: Fruit and sweet floral aroma, dark chocolate, plum,
earthy; creamy body, winy acidity.

- Sumatra Mutu Batak

Descriptively given the Indonesian name for “quality,” this bean is
produced in Lintongnihuta within Lake Toba’s southern shores. Workers
prepare the Mutu Batak bean with heavy vigilance––they are completely
sun-dried and triple-picked.

Cupping Notes: A heavy syrupy body with flavor notes of clean cedar
and tobacco.

- Panama Janson Farms Geisha

This Panama Geisha comes from the Janson Coffee Farm which is located
in the Talamanca Mountain Range near the Tisingal and Baru volcanoes
in Volcan, Panama. It is a family owned Hacienda that was established
in 1941 by Carl Axel Janson. The farm's main focus is quality
production. No pesticides, no herbicides! The balance of nutrients in
the soil comes from using enzyme micro organisms. This farm is
committed to improve and protect the environment by using solar panels
to produce the energy for the farm, reusing all excess matter from
processing for fuel and fertilizer, and seeds from the forests are
planted in the nursery for reforestation and protection of water
resources. Natural spring water is used for their Washed processing.

The Janson's processing plant was built in 1993. It was designed
specifically for specialty coffee. They do Natural and Washed
processing with updated technology added to artisanal methods to
achieve the quality you will experience in this delicious bean!

Cupping notes: Balanced, juicy, crisp, mild, and smooth with flavor
notes of milk chocolate, caramel, orange blossom, lemon, black cherry

- Costa Rica La Gladiola Tarrazu

The fruit that comprises La Gladiola comes from the Western portion of
the Tarrazu valley. The fruit is purchased from specific farmers,
process it at La Minita's mill, Beneficio del Rio Tarrazu and kept
separate from their other trademark coffee beans.

Cupping Notes: Wonderful acidity, good body with some citrus and cocoa
notes.
